args: !!python/object:argparse.Namespace
  batch_size: 16
  cloud_convert: false
  cloud_dataset_path: /home/mvries/Documents/Datasets/OPM/SingleCellFromNathan_17122021/
  dataframe_path: /home/mvries/Documents/Datasets/OPM/SingleCellFromNathan_17122021/all_data_removedwrong_ori_removedTwo.csv
  dataset_type: SingleCell
  decoder_type: foldingnetbasic
  encoder_type: dgcnn
  gpus: 1
  k: 20
  learning_rate_autoencoder: 0.0001
  mesh_dataset_path: /home/mvries/Documents/CellShape/UploadData/Dataset/TestConvert/TestMesh/
  num_epochs_autoencoder: 250
  num_features: 128
  output_dir: /home/mvries/Documents/Testing_output/
  pretrained_path: /run/user/1128299809/gvfs/smb-share:server=rds.icr.ac.uk,share=data/DBI/DUDBI/DYNCESYS/mvries/ResultsAlma/TearingNetNew/nets/dgcnn_foldingnet_128_009.pt
  proximal: 0
  tif_dataset_path: /home/mvries/Documents/CellShape/UploadData/Dataset/TestConvert/TestTiff/
